name: Flutter build

on: 
  push:
    branches: main

jobs:
  build:
    name: Build APK and Create release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '1.17.0'

    - run: flutter pub get

    - run: flutter build apk --release --split-per-abi
    - run: flutter build appbundle
    - name: Create a Release in GitHub
    - uses: actions/upload-artifact@v1
      with:
        name: Release APK
        path: build/app/outputs/apk/release/app-release.apk
